name: Build and Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'  
    
    - name: Create application archive
      run: |
        # Create a tar file with your application
        tar -czf app.tar.gz --exclude='.git' --exclude='.github' --exclude='__pycache__' --exclude='*.pyc' .
    
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create backup directory with timestamp
          BACKUP_DIR="/var/www/backup/$(date +%Y%m%d_%H%M%S)"
          mkdir -p $BACKUP_DIR
          
          # Backup current application (excluding venv)
          if [ -d "/var/www/chatbotgeneral" ]; then
            cp -r /var/www/chatbotgeneral/* $BACKUP_DIR/ 2>/dev/null || true
            # Preserve the virtual environment
            if [ -d "/var/www/chatbotgeneral/venv" ]; then
              mv /var/www/chatbotgeneral/venv /tmp/venv_backup
            fi
          fi
          
          # Clean application directory
          rm -rf /var/www/chatbotgeneral/*
          mkdir -p /var/www/chatbotgeneral
    
    - name: Copy application files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: app.tar.gz
        target: /var/www/chatbotgeneral/
    
    - name: Extract and start application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/chatbotgeneral
          
          # Extract the application
          tar -xzf app.tar.gz
          rm app.tar.gz
          
          # Restore or create virtual environment
          if [ -d "/tmp/venv_backup" ]; then
            mv /tmp/venv_backup venv
          else
            python3 -m venv venv
          fi
          
          # Install dependencies
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Stop current application
          pkill -f "uvicorn app.main:app" || true
          sleep 3
          
          # Start new application
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8090 --workers 1 > app.log 2>&1 &
          
          # Verify deployment
          sleep 5
          if pgrep -f "uvicorn app.main:app"; then
            echo "✅ Deployment successful!"
            echo "Application is running on port 8090"
          else
            echo "❌ Deployment failed!"
            echo "Logs:"
            cat app.log
            exit 1
          fi
          
          # Keep only last 5 backups
          ls -t /var/www/backup/ | tail -n +6 | xargs -r -I {} rm -rf /var/www/backup/{}
