name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create deployment script
      run: |
        cat > deploy.sh << 'EOF'
        #!/bin/bash
        set -e
        
        echo "Starting deployment..."
        cd /var/www/chatbotgeneral
        
        # Backup the existing .env file
        if [ -f ".env" ]; then
          cp .env .env.backup
        fi
        
        # Clean up unnecessary files (but keep .env)
        rm -rf .git .github __pycache__ *.pyc *.pyo
        
        # Restore .env if it was accidentally removed
        if [ -f ".env.backup" ]; then
          mv .env.backup .env
        fi
        
        # Stop current application
        echo "Stopping current application..."
        pkill -f "uvicorn app.main:app" || true
        sleep 3
        
        # Check if .env file exists
        if [ ! -f ".env" ]; then
          echo "❌ Error: .env file not found!"
          echo "Please create /var/www/chatbotgeneral/.env with required environment variables"
          exit 1
        fi
        
        # Start new application
        echo "Starting new application..."
        source venv/bin/activate
        nohup uvicorn app.main:app --host 0.0.0.0 --port 8090 > app.log 2>&1 &
        
        # Verify deployment
        sleep 5
        if pgrep -f "uvicorn app.main:app"; then
          echo "✅ Deployment successful!"
          echo "Application is running on port 8090"
        else
          echo "❌ Deployment failed!"
          echo "Application logs:"
          tail -20 app.log
          exit 1
        fi
        EOF
        chmod +x deploy.sh
    
    - name: Copy files (excluding .env)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".,deploy.sh"
        target: "/var/www/chatbotgeneral/"
    
    - name: Execute deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/chatbotgeneral
          chmod +x deploy.sh
          ./deploy.sh
